name = "pet-clinic-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
DB_HOST = "ep-damp-recipe-a8lte9zz-pooler.eastus2.azure.neon.tech"
DB_NAME = "pet-clinic"
DB_PORT = "5432"
DB_USER = "pet-clinic_owner"

[secrets]
# Set this using: wrangler secret put DB_PASSWORD
# DB_PASSWORD = "npg_okUxOygl3LH8"